### ISSUE TITLE
Qlik CLI refernces

### ISSUE THREAD

**Issue by tonikautto** [eapowertools/qs-admin-playbook#50]
**Description of Issue**
Qlik CLI has been slightly renamed to https://github.com/ahaydon/Qlik-Cli-Windows
Might be worth reviewing any reference, to not confuse with https://qlik.dev/tutorials/get-started-with-qlik-cli

**Comment by danielpilla** [comment]
Hey Toni -- all references to the "Qlik CLI" have now been updated to "Qlik CLI for Windows" for clarity.

Cheers-
